/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SettingsWebhooksRouteImport } from './routes/settings/webhooks'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'
import { Route as AdminPairingRouteImport } from './routes/admin/pairing'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminChannelsRouteImport } from './routes/admin/channels'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin/customers/$customerId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWebhooksRoute = SettingsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const AdminPairingRoute = AdminPairingRouteImport.update({
  id: '/admin/pairing',
  path: '/admin/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChannelsRoute = AdminChannelsRouteImport.update({
  id: '/admin/channels',
  path: '/admin/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AdminCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/pairing': typeof AdminPairingRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/pairing': typeof AdminPairingRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/admin': typeof AdminIndexRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/pairing': typeof AdminPairingRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/settings'
    | '/admin/analytics'
    | '/admin/channels'
    | '/admin/customers'
    | '/admin/pairing'
    | '/settings/connections'
    | '/settings/webhooks'
    | '/admin/'
    | '/chat/'
    | '/settings/'
    | '/admin/customers/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analytics'
    | '/admin/channels'
    | '/admin/customers'
    | '/admin/pairing'
    | '/settings/connections'
    | '/settings/webhooks'
    | '/admin'
    | '/chat'
    | '/settings'
    | '/admin/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/settings'
    | '/admin/analytics'
    | '/admin/channels'
    | '/admin/customers'
    | '/admin/pairing'
    | '/settings/connections'
    | '/settings/webhooks'
    | '/admin/'
    | '/chat/'
    | '/settings/'
    | '/admin/customers/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminChannelsRoute: typeof AdminChannelsRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminPairingRoute: typeof AdminPairingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/webhooks': {
      id: '/settings/webhooks'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof SettingsWebhooksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/admin/pairing': {
      id: '/admin/pairing'
      path: '/admin/pairing'
      fullPath: '/admin/pairing'
      preLoaderRoute: typeof AdminPairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/channels': {
      id: '/admin/channels'
      path: '/admin/channels'
      fullPath: '/admin/channels'
      preLoaderRoute: typeof AdminChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsWebhooksRoute: typeof SettingsWebhooksRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsWebhooksRoute: SettingsWebhooksRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface AdminCustomersRouteChildren {
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminChannelsRoute: AdminChannelsRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminPairingRoute: AdminPairingRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
